name: Example workflow for Codecov
on: [push]

jobs:
    backend-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout current commit
              uses: actions/checkout@v2

            - name: Use PHP 8.0
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
                  tools: composer
              
              - name: Run PHPUnit tests
              run: ./vendor/bin/phpunit tests --colors=always --verbose
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage1.xml,./coverage2.xml
        flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true


- name: Codecov
  uses: codecov/codecov-action@v2.1.0
